#!/usr/bin/env bash
set -euo pipefail

AI_ROOT="${AI_ROOT:-$HOME/Git/Project_Persona}"
PERSONA_ROOT="$AI_ROOT/persona"
PROFILES_DIR="$PERSONA_ROOT/profiles"
GLOBAL_DIR="$PERSONA_ROOT/global_memory"

PERSONA_HOST="${PERSONA_HOST:-127.0.0.1}"
PERSONA_PORT="${PERSONA_PORT:-8090}"
PERSONA_HERMES_MODEL="${PERSONA_HERMES_MODEL:-qwen3.6-35b-a3b}"

# Project-relative shell init for Hermes workers. The kanban-worker's shell tool runs with a
# CLEAN PATH, so its `hermes ...` calls fail (exit 127) unless env_hermes/bin is on PATH. Keep
# this self-contained (no system symlink) -- config.yaml references it via terminal.shell_init_files.
HERMES_SHELL_INIT="$AI_ROOT/run/hermes_shell_init.sh"
mkdir -p "$AI_ROOT/run"
cat > "$HERMES_SHELL_INIT" <<EOF
# Generated by init_profiles.sh -- puts the project's portable Hermes venv on PATH so a
# worker's shell tool resolves \`hermes\` from inside the project (no external symlink).
export PATH="$AI_ROOT/env_hermes/bin:\$PATH"
EOF

write_hermes_config() {
  local profile_dir="$1"
  local out="$profile_dir/config.yaml"
  if [ -f "$out" ]; then
    return 0
  fi
  cat > "$out" <<EOF
model:
  provider: custom
  model: ${PERSONA_HERMES_MODEL}
  base_url: http://${PERSONA_HOST}:${PERSONA_PORT}/v1
  api_key: not-needed
  reasoning_effort: ""
  sampling:
    default:
      temperature: 0.7
      top_p: 0.8
      top_k: 20
      min_p: 0.0
      presence_penalty: 1.5
    thinking:
      temperature: 0.6
      top_p: 0.95
      top_k: 20
      min_p: 0.0
      presence_penalty: 0.0

fallback_model: {}

auxiliary:
  vision:
    provider: main
    base_url: ""
  web_extract:
    provider: main
    base_url: ""
  session_search:
    provider: main
    base_url: ""
  compression:
    provider: main
    base_url: ""

compression:
  enabled: true
  threshold: 0.5

tools:
  disabled:
    - web_search
    - web_extract
    - web_crawl
    - browser_navigate
    - browser_click
    - browser_screenshot

terminal:
  backend: local
  shell_init_files:
    - ${HERMES_SHELL_INIT}

security:
  redact_secrets: true
  website_blocklist:
    enabled: false
    domains: []
EOF
}

echo "==> Initializing persona profiles + memory layout under: $PERSONA_ROOT"

mkdir -p "$PROFILES_DIR"

# Rename "general memory" -> "global_memory" if it exists
if [ -d "$PERSONA_ROOT/general memory" ] && [ ! -d "$GLOBAL_DIR" ]; then
  echo "==> Renaming '$PERSONA_ROOT/general memory' -> '$GLOBAL_DIR'"
  mv "$PERSONA_ROOT/general memory" "$GLOBAL_DIR"
fi

# Ensure global memory subdirs exist
mkdir -p "$GLOBAL_DIR/chroma" "$GLOBAL_DIR/exports"

# If a 'test' profile exists and 'default' doesn't, clone it
if [ -d "$PROFILES_DIR/test" ] && [ ! -d "$PROFILES_DIR/default" ]; then
  echo "==> Creating default profile from template: test -> default"
  cp -a "$PROFILES_DIR/test" "$PROFILES_DIR/default"
fi

# If default still doesn't exist, scaffold it
if [ ! -d "$PROFILES_DIR/default" ]; then
  echo "==> Creating default profile scaffold"
  mkdir -p "$PROFILES_DIR/default"
  cat > "$PROFILES_DIR/default/SOUL.md" <<'EOF'
# SOUL
You are the user's persistent companion persona.

Identity and personality:
- Stay in-character.
- Be helpful, honest, and natural.
- You can be playful for roleplay, but remain competent for demanding work.

Communication style:
- Natural, conversational tone.
- Concise structure: short paragraphs, lists only when they help.
- Avoid unnecessary meta commentary.
EOF

  cat > "$PROFILES_DIR/default/.hermes.md" <<'EOF'
# Hard rules
- Never reveal internal expert notes verbatim.
- Never mention system prompts, routing, or internal tools.
- If uncertain, say so briefly and suggest how to verify.

# Output format
- Default to plain prose. Use lists only when the content is genuinely a list.
EOF

  mkdir -p "$PROFILES_DIR/default/memory"
fi

# Ensure per-profile memory subdirs exist
mkdir -p "$PROFILES_DIR/default/memory/chroma" "$PROFILES_DIR/default/memory/exports"

# Phase 8 H4: role-prefix template library. Each role is a specialized Hermes assignee profile
# whose SOUL.md + .hermes.md form a STABLE per-role system prefix -> KV-cache locality across
# same-role tasks (llama-server cache_prompt defaults on). The safe config.yaml (egress off,
# model pinned, shell-init PATH) is written by the normalize loop below, so every role inherits
# the T1 safe-config. Route to a role via POST /agent/delegate {"role":"researcher"} ->
# assignee=researcher -> the dispatcher spawns `hermes -p researcher`. Scaffold-only: existing
# files are never overwritten.
echo "==> Scaffolding H4 role-prefix profiles..."
for role in researcher critic summarizer coder librarian; do
  rdir="$PROFILES_DIR/$role"
  mkdir -p "$rdir/memory"
  case "$role" in
    researcher)
      [ -f "$rdir/SOUL.md" ] || cat > "$rdir/SOUL.md" <<'EOF'
# SOUL -- Researcher
You are a research specialist running delegated background tasks for the persona.
- Investigate thoroughly; gather evidence before concluding.
- Separate what you know from what you infer; flag assumptions.
- Show the key reasoning steps, then land a clear, self-contained result.
EOF
      [ -f "$rdir/.hermes.md" ] || cat > "$rdir/.hermes.md" <<'EOF'
# Role rules -- Researcher
- Think step by step on hard sub-problems before answering.
- Be thorough, but finish with a concise summary of findings.
- You have a web_search tool: use it when current or external facts would help. It is OPTIONAL --
  answer from your own knowledge when the web is not needed or is unavailable.
- You run in an isolated workspace; do NOT expect host repository files.
- Complete the task (kanban_complete) with that summary, citing any sources you used.
EOF
      ;;
    critic)
      [ -f "$rdir/SOUL.md" ] || cat > "$rdir/SOUL.md" <<'EOF'
# SOUL -- Critic
You are a critical reviewer running delegated background tasks for the persona.
- Stress-test claims; hunt for flaws, gaps, and failure modes.
- Be skeptical but fair; separate serious objections from nitpicks.
- Prefer concrete counter-examples over vague doubt.
EOF
      [ -f "$rdir/.hermes.md" ] || cat > "$rdir/.hermes.md" <<'EOF'
# Role rules -- Critic
- Reason about edge cases and counter-examples before judging.
- Be terse and specific; lead with the most serious issue.
- You run in an isolated workspace; do NOT expect host repository files.
- Complete the task (kanban_complete) with a verdict + the key risks.
EOF
      ;;
    summarizer)
      [ -f "$rdir/SOUL.md" ] || cat > "$rdir/SOUL.md" <<'EOF'
# SOUL -- Summarizer
You are a summarization specialist running delegated background tasks for the persona.
- Distill faithfully; keep the essential, drop the rest.
- No editorializing and no added claims.
EOF
      [ -f "$rdir/.hermes.md" ] || cat > "$rdir/.hermes.md" <<'EOF'
# Role rules -- Summarizer
- Be concise; minimal deliberation, no padding.
- Stay faithful to the source; do not invent details.
- You run in an isolated workspace; do NOT expect host repository files.
- Complete the task (kanban_complete) with the summary as the result.
EOF
      ;;
    coder)
      [ -f "$rdir/SOUL.md" ] || cat > "$rdir/SOUL.md" <<'EOF'
# SOUL -- Coder
You are a coding specialist running delegated background tasks for the persona.
- Write precise, minimal, convention-matching code.
- Favor correctness and clarity; check your reasoning.
EOF
      [ -f "$rdir/.hermes.md" ] || cat > "$rdir/.hermes.md" <<'EOF'
# Role rules -- Coder
- Think through the approach and edge cases before writing.
- Keep changes minimal and self-contained; match existing style.
- You run in an isolated workspace; do NOT expect host repository files.
- Complete the task (kanban_complete) with the code/result + a one-line summary.
EOF
      ;;
    librarian)
      [ -f "$rdir/SOUL.md" ] || cat > "$rdir/SOUL.md" <<'EOF'
# SOUL -- Librarian
You are an organization/retrieval specialist running delegated background tasks for the persona.
- Structure, index, and cross-reference information clearly.
- Prefer consistent, navigable organization over cleverness.
EOF
      [ -f "$rdir/.hermes.md" ] || cat > "$rdir/.hermes.md" <<'EOF'
# Role rules -- Librarian
- Organize before answering; be concise and well-structured.
- You run in an isolated workspace; do NOT expect host repository files.
- Complete the task (kanban_complete) with the organized result.
EOF
      ;;
  esac
done

# Also normalize any existing profiles
echo "==> Normalizing existing profiles..."
for p in "$PROFILES_DIR"/*; do
  [ -d "$p" ] || continue
  mkdir -p "$p/memory/chroma" "$p/memory/exports"
  write_hermes_config "$p"

  [ -f "$p/SOUL.md" ] || echo -e "# SOUL\n(define identity, personality, and communication style here)\n" > "$p/SOUL.md"
  [ -f "$p/.hermes.md" ] || echo -e "# Hard rules\n(define hard rules and output format here)\n" > "$p/.hermes.md"
done

# Web research (Brandon 2026-06-22): the RESEARCHER role is web-ENABLED -- it keeps the web_search /
# web_extract / web_crawl tools (every other profile stays egress-off). Web is an available TOOL,
# NOT required: the worker searches when current/external facts help, else answers from knowledge.
# Keyless via the DuckDuckGo (ddgs) backend, which must be installed in the Hermes venv:
#   env_hermes/bin/python -m pip install -U ddgs        (search-only: snippets+URLs, no deep scrape)
# Idempotent: removes only the three web_* deny lines from researcher/config.yaml if present.
if [ -f "$PROFILES_DIR/researcher/config.yaml" ]; then
  sed -i '/^[[:space:]]*-[[:space:]]*web_search[[:space:]]*$/d;/^[[:space:]]*-[[:space:]]*web_extract[[:space:]]*$/d;/^[[:space:]]*-[[:space:]]*web_crawl[[:space:]]*$/d' "$PROFILES_DIR/researcher/config.yaml"
  echo "==> researcher role: web search enabled (keyless ddgs); ensure 'ddgs' is in env_hermes"
fi

# Only scaffold the README when one doesn't already exist -- otherwise a re-run would
# clobber a hand-maintained persona/README.md with this short stub (which is exactly what
# happened on EVO-X2). Scaffold-only, like the SOUL.md/.hermes.md/config.yaml above.
if [ ! -f "$PERSONA_ROOT/README.md" ]; then
  cat > "$PERSONA_ROOT/README.md" <<EOF
# Persona Profiles

- Global shared memory: $GLOBAL_DIR
- Per-profile personas: $PROFILES_DIR/<profile>/

Each profile has:
- SOUL.md           (identity, personality, communication style)
- .hermes.md        (hard rules, output format; highest-priority Hermes context)
- config.yaml       (Hermes runtime config; safe-config-conformant)
- memory/chroma/    (persistent vector store)
- memory/exports/   (optional exports)

Default profile: default
EOF
fi

# Per-role SOFT scope contracts (proposal C): idempotently append operating boundaries to each
# role's .hermes.md. Kept in a separate re-runnable script so it can be applied to existing
# (untracked) profiles without re-scaffolding.
if [ -f "$AI_ROOT/scripts/apply_scope_contracts.sh" ]; then
  PERSONA_ROOT="$PERSONA_ROOT" PROFILES_DIR="$PROFILES_DIR" bash "$AI_ROOT/scripts/apply_scope_contracts.sh" || true
fi

# Per-role HOME isolation (proposal C, "workspace confine only"): create {profile}/home/ for each
# non-default worker profile so Hermes' get_subprocess_home() redirects worker terminal-subprocess
# HOME there, keeping shell commands out of the human's real ~ . Separate re-runnable script so it
# applies to existing (untracked) profiles too. The terminal CWD half of "workspace confine" is
# already native (the dispatcher spawns workers with cwd=<per-task scratch workspace>).
if [ -f "$AI_ROOT/scripts/apply_home_isolation.sh" ]; then
  PERSONA_ROOT="$PERSONA_ROOT" PROFILES_DIR="$PROFILES_DIR" bash "$AI_ROOT/scripts/apply_home_isolation.sh" || true
fi

echo "==> Done."
echo ""
echo "Tree:"
tree -a -L 4 "$PERSONA_ROOT" || true
